version: 2

jobs:
  build:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
      - run:
          command: |
            pip3 install --user online-judge-tools
            ./test_oj/test_oj.sh